name: profile_app
description: "Oryza's Profile App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/oryza_background.png
    - assets/images/porto1.JPG
    - assets/images/porto2.jpg
    - assets/images/porto3.JPG
    - assets/images/porto4.jpg
    - assets/images/porto5.jpg